### ISSUE TITLE
Font Changes

### ISSUE THREAD

**Issue by colevscode** [jboolean/art-coop#56]
sruti said: "there's some font changing to be done. we use 2 types of caudex and 2 types of rubik. laid out in original document"

**Comment by colevscode** [comment]
You can visit this link to provide feedback on fonts 

https://redpen.io/fa20982e2773e0022a

**Comment by colevscode** [comment]
The website fonts use a different sizing system than the doc. Currently the web fonts are specified in pixels, where the doc is specified in points. There are several different web font sizes in use from 16px to 32px, and I introduced a larger font size for the main section headers (48px). Maybe the easiest way to handle this is to just to let me know which parts of the webpage are too small or too large. If you want you can just annotate the above linked image to let me know which fonts are the wrong size.

**Comment by carolineawoolard** [comment]
Done - go forth from here.

**Comment by colevscode** [comment]
Ok generally resolved these issues I think. I'm following [this type scale](https://type-scale.com/?size=16&scale=1.414&text=A+Visual+Type+Scale&webfont=Open%2BSans&font-family=%27Open+Sans%27,+sans-serif&font-weight=400&font-family-headers&font-weight-headers=inherit&background-color=white&font-color#333), which is pretty much what Julian had in place already, just a slightly larger body font.

* I made the body font larger (18px, up from 16px)
* I converted the sub section headers to rubix bold 24px
* I converted the main section headers to caudex bold 32px
* I kept the welcome section slightly larger (24px) so that it has a bit more presence. I can make it smaller if you prefer.
* I also went through and adjusted various section content to match your comments in the redpen.

See https://github.com/jboolean/art-coop/commit/7fabc6377046963d86ba4d2e81dc366f9a253870
