### ISSUE TITLE
Update budgeting examples

### ISSUE THREAD

**Issue by colevscode** [jboolean/art-coop#57]
sruti said: "sliding graphic with participatory budgeting examples + more needs to be moved. content in this whole section i think needs to be amended?"

**Comment by colevscode** [comment]
Where should this section be moved to? How should it be ammended?

**Comment by carolineawoolard** [comment]
@ssuryanar I leave this to you to explain -- looks ok to me and @colevscode it's ok to push it live after you make the type edits as we have a big event next weekend where we'd love to show this off

**Comment by ssuryanar** [comment]
hiya! i meant this:
<img width="1223" alt="Screen Shot 2022-09-05 at 10 46 48 AM" src="https://user-images.githubusercontent.com/66737965/188474869-3edb9667-dc70-4e60-9a79-1d8d6ebe8862.png">

It should go UNDER directory:
Join our Process Potlucks and the Arts Culture and Care Working Group, led by Marina Lopez, Robin Bean Crane, and Ebony Gustave.

Directory

We're working on a directory to help our community navigate the solidarity economy and its culture bearers.

Write to [sruti@art.coop](mailto:sruti@art.coop) to learn more!
<img width="1223" alt="Screen Shot 2022-09-05 at 10 46 48 AM" src="https://user-images.githubusercontent.com/66737965/188475042-cf7c08d1-e268-485d-a1e6-10b6e4d5391e.png">

**Comment by colevscode** [comment]
Ok, moved. See https://github.com/jboolean/art-coop/commit/053fe819d5e9ba58dc517b0500634dbb25ca7f96
