### ISSUE TITLE
Text edit to support

### ISSUE THREAD

**Issue by carolineawoolard** [jboolean/art-coop#58]
Edit from: 

"This **report** is made possible by the William and Flora Hewlett Foundation, the Kenneth Rainin Foundation, the Barr Foundation, and the Mellon Foundation."

To say:

"Art.coop is a fiscally sponsored project of Open Collective Foundation. Our budget is transparent and available online [here](https://opencollective.com/study-into-action/transactions). Support comes from individual contributors like you as well as the William and Flora Hewlett Foundation, the Kenneth Rainin Foundation, the Barr Foundation, and the Mellon Foundation."

<img width="1165" alt="Screen Shot 2022-09-04 at 11 09 24 AM" src="https://user-images.githubusercontent.com/88373348/188306135-760e9649-a7e9-4ce2-ba00-7150e591ce14.png">

**Comment by colevscode** [comment]
Done. https://github.com/jboolean/art-coop/commit/534cdc8be335179fcc4abed45e764ca59b096ca3
