### ISSUE TITLE
remove first graphic (it is already below)

### ISSUE THREAD

**Issue by carolineawoolard** [jboolean/art-coop#59]
This image is what is causing a lot of type confusion as it scales as an image rather than vector. We ALREADY have this text below, so you can remove it completely. 
<img width="949" alt="Screen Shot 2022-09-04 at 12 06 07 PM" src="https://user-images.githubusercontent.com/88373348/188308205-d37e32b2-4d73-4f38-b4ba-bcf689863b38.png">

**Comment by colevscode** [comment]
Done in https://github.com/jboolean/art-coop/commit/7fabc6377046963d86ba4d2e81dc366f9a253870
