### ISSUE TITLE
replace emojis with custom emojis from our illustrator and link to sections

### ISSUE THREAD

**Issue by carolineawoolard** [jboolean/art-coop#60]
Replace the emojis with custom illustrations that scale (if possible - not that amplify and study pngs are labeled wrong) and 

![art coop_future_graphics_SMALL_amplify](https://user-images.githubusercontent.com/88373348/188308288-1680f8fd-ccba-4510-838b-d3f93ab11439.png)
![art coop_future_graphics_SMALL_study](https://user-images.githubusercontent.com/88373348/188308295-1796b8f1-2bfe-403d-b567-1f82e41d820a.png)
![art coop_future_graphics_move money](https://user-images.githubusercontent.com/88373348/188308302-e8ac8b9c-e72b-4be5-a42c-63fbb5915a25.png)
![art coop_future_graphics_SMALL_connect](https://user-images.githubusercontent.com/88373348/188308305-72c8487f-a513-498d-ad25-ce64bde499f2.png)
each of these sections - study, connect, amplify, and move money should link to that section of the site.

[📚](https://site-update-2022.art.coop/#) STUDY together to practice ways of spreading power and wealth and rooting it in community,
[♥️](https://site-update-2022.art.coop/#connect) CONNECT cultural innovators across silos in the solidarity economy movement,
[📣](https://site-update-2022.art.coop/#amplify) AMPLIFY research, inspiration, resources, and events, and
[💰](https://site-update-2022.art.coop/#movemoney) MOVE MONEY to multi-year, self-determined, systems-change work.

<img width="1185" alt="Screen Shot 2022-09-04 at 12 08 38 PM" src="https://user-images.githubusercontent.com/88373348/188308250-7f18bcfe-8a74-4a8a-9284-69449b10dcce.png">

**Comment by colevscode** [comment]
Completed in e5eddb3aca0a7d29dfab9cc0023c3861f6897a5e
