### ISSUE TITLE
move "top 10 resources" below "report"

### ISSUE THREAD

**Issue by carolineawoolard** [jboolean/art-coop#61]
top 10 resources is geared for grantmakers, not artists, and needs to go below the Report section. Right now it is under the fixed area right after the intro to the Study section.

[Resources](http://art.coop/#resources)
Learn more from Art.coop about the ways that creatives strengthen the Solidarity Economy.
<img width="1078" alt="Screen Shot 2022-09-04 at 12 58 28 PM" src="https://user-images.githubusercontent.com/88373348/188309971-081b6489-3d60-4c2c-b4b6-2f2f309e1453.png">

**Comment by colevscode** [comment]
Ok, I think this is what you mean, but not totally confident. 7595eb4d98c6a1331dea1348e51a90774c3c1a32
