### ISSUE TITLE
embed instagram feed (or twitter if you prefer) under Amplify

### ISSUE THREAD

**Issue by carolineawoolard** [jboolean/art-coop#62]
This image is a stand-in for the embed of our twitter or IG

Instagram: [@_artcoop](https://www.instagram.com/_artcoop/)
Twitter: [@_artcoop](https://twitter.com/_artcoop)

<img width="890" alt="Screen Shot 2022-09-04 at 1 01 22 PM" src="https://user-images.githubusercontent.com/88373348/188310010-f46096e0-1062-4ae4-95f9-ee5906d11a69.png">

**Comment by ssuryanar** [comment]
yes! this is what I meant by IG @colevscode

**Comment by colevscode** [comment]
Added insta feed at 121e3cb9db423a91c931370eae0c5a20afeb64b5

Note: This is a free [elfsight](https://apps.elfsight.com/) embed. It maxes out at 200 views per month. If you get a lot of traffic you'll need to upgrade. (plans [here](https://apps.elfsight.com/panel/applications/instashow/)) Also it's using my temp account. Y'all should probably create an account, and send me the login credentials so I can set this up on your account.
